import 'dart:ui';

class AppColor {
  static const scaffoldColor = Color(0xFFFFFFFF);
  static const white = Color(0xFFFFFFFF);
  static const mediumGray = Color(0xff777777);
  static const darkGrey = Color(0xffA1A1A1);
  static const brightGray = Color(0xffEDF1F4);
  static const softWhiteGray = Color(0xffF6F6F6);
  static const borderLightGrey = Color(0xffD0D0D0);
  static const mediumLightGray = Color(0xffACACAC);
  static const gray84 = Color(0xFF6D6D6D);
  static const lightGray = Color(0xFFF2F2F2);
  static const leftArrow = Color(0xFFF5F5F5);
  static const mildBlack = Color(0xFF252525);
  static const thinBlack = Color(0xff1B1A1A);
  static const black = Color(0xFF000000);
  static const lightSkyBlue = Color(0xFFE6F2F9);
  static const royalBlue = Color(0xFF297CF1);
  static const skyBlue = Color(0xFF2C8DD1);
  static const iceBlue = Color(0xFFF4FAFF);
  static const brightBlue = Color(0xff1C71FD);
  static const electricSkyBlue = Color(0xff41CEFF);
  static const shadowBlue = Color(0x1A0096FF);
  static const darkBlue = Color(0xff071016);
  static const blueGradient1 = Color(0xff0797FD);
  static const lowLightBlue = Color(0xffE4F4FF);
  static const mediumGreen = Color(0xFF31CC64);
  static const green = Color(0xff31CC64);
  static const lightGreen = Color(0xffE6F9EC);
  static const red = Color(0xffF5465C);
  static const resendOtp = Color(0xff2C8DD1);
  static const lightSilver = Color(0xffD0D0D0);
  static const lavenderMist = Color(0xffEBEFFF);
  static const appOfferArrow = Color(0xffDC8A2B);
  static const surpriseOfferArrow = Color(0xff648E15);
  static const floralWhite = Color(0xffF5F9F5);
  static const papayaWhip = Color(0xffFFEFDB);
  static const white3 = Color(0xffF1F1F1);
  static const red1 = Color(0xffDA4141);
  static const border = Color(0xffE7EBEE);
}
